services:

    knit:
        class: Splot\KnitModule\Knit\Knit
        arguments:
            - @knit.stores.default
            - @knit.entity_finder
    
    knit.entity_finder:
        class: Splot\KnitModule\Knit\EntityFinder
        arguments:
            - @application

    # extensions

    knit.extension.softdeletable:
        class: Knit\Extensions\Softdeletable
        arguments:
            - @knit
        notify:
            - ["@knit", "registerExtension", ["softdeletable", "@"]]
